exclude = [
    "clang_tidy",
    "device/esp_tinyusb/test_apps/usb_cv",
]
recursive = true
manifest_file = ".build-test-rules.yml"
check_warnings = true

# build related options
build_dir = "build_@t_@w"

# config rules
config_rules = [
    'sdkconfig.ci=default',
    'sdkconfig.ci.*=',
    '=default',
]
